### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by JustSxm** [Ailyrr/HelValorantOverlay#1]
Hello,

Is there any discord to follow the development of this project?

Thanks!

**Comment by Ailyrr** [comment]
Hi there ! Thank you for your interest in my project, it makes me happy to see people interested in what I make  :D

Unfortunately I haven't created a discord for this project as I didn't think that a lot of people would be actively searching for this kind of system. If there is more demand I'll gladly create one for future updates and community feedback on the system.

Hope this clears things !
Cheers,
Cornell
